@echo off
rem Zapusk prilozheniya "Merch NGU". Dvoynoy klik po etomu faylu.
rem Vsyo obshchenie s polzovatelem idet iz Python i iz okna Windows -
rem sam .bat ostayotsya v ASCII, chtoby ne zaviset ot kodirovki konsoli.
cd /d "%~dp0"

set "PY="
where pythonw.exe >nul 2>&1 && set "PY=pythonw.exe"
if not defined PY where py.exe >nul 2>&1 && set "PY=py.exe -3w"
if not defined PY where python.exe >nul 2>&1 && set "PY=python.exe"
if not defined PY goto nopython

start "" %PY% "%~dp0run.py"
exit /b 0

:nopython
powershell -NoProfile -ExecutionPolicy Bypass -EncodedCommand QQBkAGQALQBUAHkAcABlACAALQBBAHMAcwBlAG0AYgBsAHkATgBhAG0AZQAgAFMAeQBzAHQAZQBtAC4AVwBpAG4AZABvAHcAcwAuAEYAbwByAG0AcwAgAHwAIABPAHUAdAAtAE4AdQBsAGwACgBbAFMAeQBzAHQAZQBtAC4AVwBpAG4AZABvAHcAcwAuAEYAbwByAG0AcwAuAE0AZQBzAHMAYQBnAGUAQgBvAHgAXQA6ADoAUwBoAG8AdwAoACIAFAQ7BE8EIABABDAEMQQ+BEIESwQgAD0EQwQ2BDUEPQQgAFAAeQB0AGgAbwBuACAAFCAgAD4EPQQgADUESQRRBCAAPQQ1BCAAQwRBBEIEMAQ9BD4EMgQ7BDUEPQQuAGAAbgBgAG4AIQQ1BDkERwQwBEEEIAA+BEIEOgRABD4ENQRCBEEETwQgAEEEQgRABDAEPQQ4BEYEMAQgADcEMAQzBEAEQwQ3BDoEOAQuACAAIQQ6BDAERwQwBDkEQgQ1BCAAUAB5AHQAaABvAG4AIAA4BCAAPwRABDgEIABDBEEEQgQwBD0EPgQyBDoENQQgAD4EMQRPBDcEMARCBDUEOwRMBD0EPgQgAD8EPgRBBEIEMAQyBEwEQgQ1BCAAMwQwBDsEPgRHBDoEQwQgAKsAQQBkAGQAIABwAHkAdABoAG8AbgAuAGUAeABlACAAdABvACAAUABBAFQASAC7AC4AYABuAGAAbgAfBD4EQQQ7BDUEIABDBEEEQgQwBD0EPgQyBDoEOAQgAEEEPQQ+BDIEMAQgADcEMAQ/BEMEQQRCBDgEQgQ1BCAATQRCBD4EQgQgAE8EQAQ7BEsEOgQuACIALAAiABwENQRABEcEIAAdBBMEIwQiACwAMAAsADQAOAApACAAfAAgAE8AdQB0AC0ATgB1AGwAbAAKAFMAdABhAHIAdAAtAFAAcgBvAGMAZQBzAHMAIAAiAGgAdAB0AHAAcwA6AC8ALwB3AHcAdwAuAHAAeQB0AGgAbwBuAC4AbwByAGcALwBkAG8AdwBuAGwAbwBhAGQAcwAvACIACgA=
exit /b 1
